# Generated by Django 4.2.7 on 2023-12-31 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes_app', '0002_clienteapp_responsavel_alter_clienteapp_produto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clienteapp',
            name='responsavel',
        ),
    ]
