# Generated by Django 4.2.7 on 2023-12-31 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes_app', '0003_remove_clienteapp_responsavel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clienteapp',
            name='cliente_kronos',
        ),
    ]
