# Generated by Django 4.2.7 on 2023-12-31 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes_kronos', '0003_alter_cliente_logo'),
        ('clientes_app', '0004_remove_clienteapp_cliente_kronos'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienteapp',
            name='cliente_kronos',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='clientes_kronos.cliente'),
            preserve_default=False,
        ),
    ]
