# Generated by Django 4.2.7 on 2023-12-31 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes_app', '0005_clienteapp_cliente_kronos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clienteapp',
            name='cliente_kronos',
        ),
    ]
