# Generated by Django 4.2.7 on 2023-12-31 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes_app', '0007_clienteapp_responsavel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clienteapp',
            name='produto',
        ),
    ]
