from django.db import models

class Bd477(models.Model):
    #codigo = models.IntegerField(primary_key=True)

    NUMLANCTO = models.TextField()
    PARCELA = models.TextField()
    EVENTO = models.TextField()
    DESCR_EVENTO = models.TextField()
    HISTORICO_DA_DESPESA = models.TextField()
    CNPJ_FORNECEDOR = models.TextField()
    NOME_FORNECEDOR = models.TextField()
    MUNICIPIO_FORNECEDOR = models.TextField()
    UF_FORNECEDOR = models.TextField()
    BCO_AGENCIA_CONTA_FORNECEDOR = models.TextField()
    CNPJ_FAVORECIDO = models.TextField()
    NOME_FAVORECIDO = models.TextField()
    ESPECIALIDADE = models.TextField()
    RNTRC = models.TextField()
    CTA_CTB_DEB = models.FloatField()
    CTA_CTB_CRED = models.FloatField()
    NFISCAL = models.IntegerField()
    CHAVE_NFISCAL = models.FloatField()
    VALOR_TOTAL_PRODUTOS = models.FloatField()
    VLR_NOTA = models.FloatField()
    VLR_PARCELA = models.FloatField()
    JUROS = models.FloatField()
    DESCONTOS = models.FloatField()
    VLR_FINAL = models.FloatField()
    INCLUSAO = models.DateTimeField()
    LOGIN = models.TextField()
    VENCIMEN = models.DateTimeField()
    EMISSAO = models.DateTimeField()
    DATA_PGTO = models.DateTimeField()
    APROVACAO = models.TextField()
    CONTABIL = models.DateTimeField()
    UNI = models.TextField()
    SIT_DES = models.TextField()
    ARQ_REMESSA = models.FloatField()
    ARQ = models.FloatField()
    COD_BAR_BLOQUETO = models.FloatField()
    CFOP = models.FloatField()
    GRUPO_EVENTO = models.TextField()
    MES_COMPETENCIA = models.DateTimeField()
    cod = models.CharField(max_length=255, blank=True, null=True)
    data_hora_import = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return self.NUMLANCTO
