# Generated by Django 4.1.7 on 2023-12-11 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app477', '0003_alter_bd477_nfiscal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bd477',
            name='cod',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
