# Generated by Django 4.1.7 on 2023-12-11 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app477', '0004_alter_bd477_cod'),
    ]

    operations = [
        migrations.AddField(
            model_name='bd477',
            name='data_hora_import',
            field=models.DateTimeField(auto_now_add=True, max_length=255, null=True),
        ),
    ]
