# Generated by Django 4.1.7 on 2023-12-11 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app477', '0006_alter_bd477_data_hora_import'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bd477',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
