# Generated by Django 4.1.7 on 2023-12-11 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app477', '0008_alter_bd477_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bd477',
            old_name='data_hora_import',
            new_name='_data_hora_import',
        ),
    ]
