# Generated by Django 4.1.7 on 2023-12-11 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app477', '0009_rename_data_hora_import_bd477__data_hora_import'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bd477',
            old_name='_data_hora_import',
            new_name='data_hora_import',
        ),
    ]
