# Generated by Django 4.2.7 on 2023-11-27 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filiais', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filial',
            name='sigla',
            field=models.CharField(default=0, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
