# Generated by Django 4.2.7 on 2023-11-27 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes_kronos', '0003_alter_cliente_logo'),
        ('filiais', '0002_filial_sigla'),
    ]

    operations = [
        migrations.AddField(
            model_name='filial',
            name='cliente',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, related_name='filiais', to='clientes_kronos.cliente'),
            preserve_default=False,
        ),
    ]
