# Generated by Django 4.2.7 on 2023-11-18 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes_kronos', '0001_initial'),
        ('accounts', '0002_customuser_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='clientes_kronos.cliente'),
        ),
    ]
