# Generated by Django 4.2.7 on 2023-12-29 02:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('produtos', '0001_initial'),
        ('clientes_kronos', '0003_alter_cliente_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('AG', 'Aguardando'), ('CO', 'Concluído'), ('EA', 'Em Atraso')], default='AG', max_length=2)),
                ('descricao', models.TextField()),
                ('prazo', models.DateField()),
                ('area', models.CharField(choices=[('FI', 'Financeiro'), ('PE', 'Pessoal'), ('PR', 'Processos'), ('CO', 'Comercial')], max_length=2)),
                ('cliente_kronos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarefas_kronos', to='clientes_kronos.cliente')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='produtos.produto')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
