# Generated by Django 4.2.7 on 2023-11-19 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientes_kronos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fornecedor', models.CharField(max_length=100)),
                ('cnpj_fornecedor', models.CharField(max_length=18)),
                ('numero_nf', models.CharField(max_length=20)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_emissao_nf', models.DateField()),
                ('descricao', models.TextField()),
                ('arquivo_nf', models.FileField(upload_to='notas_fiscais/')),
                ('cliente_associado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes_kronos.cliente')),
                ('usuario_cadastrou', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
