# Generated by Django 4.2.7 on 2023-11-20 01:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('protocolo_notas_fiscais', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notafiscal',
            name='status_ssw',
            field=models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], default='nao', max_length=3),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='usuario_que_mudou_o_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nf_status_modificador', to=settings.AUTH_USER_MODEL),
        ),
    ]
