# Generated by Django 4.2.7 on 2023-11-20 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocolo_notas_fiscais', '0002_notafiscal_status_ssw_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notafiscal',
            name='data_ultima_alteracao',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
