# Generated by Django 4.2.7 on 2023-11-20 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocolo_notas_fiscais', '0003_notafiscal_data_ultima_alteracao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notafiscal',
            name='data_ultima_alteracao',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
