# Generated by Django 4.1.7 on 2023-11-20 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocolo_notas_fiscais', '0004_alter_notafiscal_data_ultima_alteracao'),
    ]

    operations = [
        migrations.AddField(
            model_name='notafiscal',
            name='data_status_ssw',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
