# Generated by Django 4.1.7 on 2023-11-24 20:13

from django.db import migrations, models
import protocolo_notas_fiscais.models


class Migration(migrations.Migration):

    dependencies = [
        ('protocolo_notas_fiscais', '0005_notafiscal_data_status_ssw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notafiscal',
            name='arquivo_nf',
            field=models.FileField(upload_to=protocolo_notas_fiscais.models.RenameNFFile('notas_fiscais/')),
        ),
    ]
