# Generated by Django 4.1.7 on 2023-11-27 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocolo_notas_fiscais', '0006_alter_notafiscal_arquivo_nf'),
    ]

    operations = [
        migrations.AddField(
            model_name='notafiscal',
            name='boleto',
            field=models.FileField(null=True, upload_to='boletos/'),
        ),
    ]
