# Generated by Django 4.2.7 on 2023-12-07 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocolo_notas_fiscais', '0010_alter_notafiscal_boleto'),
    ]

    operations = [
        migrations.AddField(
            model_name='notafiscal',
            name='cod',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
