# Generated by Django 4.1.7 on 2023-11-24 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes_kronos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos_clientes/'),
        ),
    ]
