# Generated by Django 4.1.7 on 2023-11-24 20:25

import clientes_kronos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes_kronos', '0002_cliente_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=clientes_kronos.models.RenameLogo('static/logos_clientes/')),
        ),
    ]
